imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    translator: { fallback: en }
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id: ~
    fragments: ~
    http_method_override: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        # other form themes
        - 'bootstrap_3_layout.html.twig'
        - 'VichUploaderBundle:Form:fields.html.twig'
# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.root_dir%/data/data.db3'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    encryption: "%mailer_encryption%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    auth_mode: "%mailer_auth_mode%"
    spool: { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: secured_area
    user_class: AppBundle\Entity\User
    service:
        mailer: fos_user.mailer.twig_swift
    profile:
        form:
            type:  AppBundle\Form\ProfileType
    registration:
        form:
            type: AppBundle\Form\UserType
        confirmation:
            enabled: true
            template:   '@FOSUser/Registration/email.txt.twig'
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"
hwi_oauth:
    firewall_names: [secured_area]
    connect:
        confirmation: false
        account_connector: custom.social.user_provider
    fosub:
        username_iterations: 30
        properties:
            facebook:    facebookId
    resource_owners:
        facebook:
            type:                facebook
            client_id:           152447985163006
            client_secret:       2babaf86e80c38131f5a5cc510e9aff7
            scope:         "email"
            infos_url:     "https://graph.facebook.com/me?fields=id,name,email,picture.type(large)"
            paths:
                email:          email
                profilepicture: picture.data.url
                identifier: id
            options:
                display: popup
                auth_type: rerequest
                csrf: true
vich_uploader:
    db_driver: orm # or mongodb or propel or phpcr
    mappings:
        thumbnail_post:
            uri_prefix:         /uploads/images
            upload_destination: '%thumbnail_post_upload%'
            namer:              vich_uploader.namer_origname
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
        user_avatar:
            uri_prefix:         /uploads/user
            upload_destination: '%user_avatar_upload%'
            namer:              vich_uploader.namer_origname
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
ivory_ck_editor:
    configs:
        ck_blog_config:
            toolbar: full
            uiColor: "#ffffff"
