app:
    resource: '@AppBundle/Controller/'
    type: annotation
homepage:
    path: /
    defaults: { _controller: AppBundle:Home:index }
post_index:
    path: /page/
    defaults: { _controller: AppBundle:Blog:index, page: 1 }
post_show:
    path: /page/{page}
    defaults: { _controller: AppBundle:Blog:index, page: 1 }
    requirements:
        page:  \d+
about:
    path: /about/
    defaults: { _controller: AppBundle:Home:about }

post_detail:
    path: /post/{slug}
    defaults: { _controller: AppBundle:Blog:postShow }

showuser:
    path: /show_user/
    defaults: { _controller: AppBundle:User:showUser }
deleteuser:
    path: /show_user/delete/{id}
    defaults: { _controller: AppBundle:User:deleteUser}

admin:
    path: /admin/
    defaults: { _controller: AppBundle:BlogAdmin:index}
admin_createPost:
    path: /admin/create_post
    defaults: { _controller: AppBundle:BlogAdmin:createPost}
admin_editPost:
    path: /admin/edit_post/{id}
    defaults: { _controller: AppBundle:BlogAdmin:editPost}
admin_deletePost:
    path: /admin/delete_post/{id}
    defaults: { _controller: AppBundle:BlogAdmin:deletePost}


fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register
fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile
fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
fos_user_security_login:
    path:      /login/
    defaults:  { _controller: FOSUserBundle:Security:login, _method: POST }
fos_user_security_logout:
    path:      /logout
    defaults:  { _controller: FOSUserBundle:Security:logout, _method: POST }
fos_user_security_check:
    path: /login/check-email
profile_avatar_edit_ajax:
    path:      /profile/edit/ajax
    defaults:  { _controller: AppBundle:Profile:avatarEdit }

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /social/connect
hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /social/connect
#hwi_oauth_login:
#    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
#    prefix:   /social/login
facebook_login:
    path: /social/login/check-facebook