# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value
services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    slugger:
        class: AppBundle\Utils\Slugger
    markdown:
        class: AppBundle\Utils\MarkDown
    app.twig.app.extension:
        public:    false
        class:     AppBundle\Twig\AppExtension
        arguments: ['@markdown']
        tags:
            - { name: twig.extension }
    app.twig.intl_extension:
        public: false
        class:  Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
    custom.social.user_provider:
        class:        AppBundle\Security\Core\User\MyFOSUBUserProvider
        arguments: ['@fos_user.user_manager', { facebook: facebookId }]
    app.bundle.service:
        class:  AppBundle\Service\MyFirstService
        arguments:
            - "@service_container"
            - "@session"

    #App Exception Redirect 404
#    app.exception_listener:
#            class: AppBundle\EventListener\ExceptionListener
#            tags:
#                - { name: kernel.event_listener, event: kernel.exception }